### ISSUE TITLE
Plugin installation was unsuccessful due to error "Cannot parse records: Unexpected token ,"

### ISSUE THREAD

**Issue by pchanas** [stormpython/tagcloud#10]
Hi
We began to have this error on one of our environments last week when installing tagcloud plugin.
The zip file is ok (tested on other env)... does anyone have any idea of the potential root cause?
We are in Kibana 4.5.0.
Thanks in advance
P.

**Comment by stormpython** [comment]
@pchanas Can you copy paste the stack trace?

**Comment by pchanas** [comment]
Hi, sorry for the delay
Unfortunately we don't have the trace anymore.
We solved the isse by upgrading Kibana (to 4.5.2).
Cheers
P
