### ISSUE TITLE
Kibana 5.0

### ISSUE THREAD

**Issue by ranahaarb** [stormpython/tagcloud#12]
are you have any plan to update tag cloud for kibana 5?

**Comment by t3chn0m4g3** [comment]
+1

**Comment by marfago** [comment]
+1

**Comment by ranahaarb** [comment]
It works for kibana 5, only with a bit changes:
In the file "tagcloud/public/cloud.js", line 6 and 7 must be changed to:

`var TemplateVisType = Private(require('ui/template_vis_type/template_vis_type'));
  var Schemas = Private(require('ui/vis/schemas'));
`

**Comment by OzWookiee** [comment]
There seems to be issues with the installation of plugins between 4.x and 5.0 so not only will it need this update but apparently something in gulp needs to be changed also.

**Comment by stormpython** [comment]
Given that the core Kibana team is working on implementing a [tag cloud](https://github.com/elastic/kibana/pull/8104) visualization (which modifies this plugin for Kibana 5.0), I don't have any plans to update this for Kibana 5.
