### ISSUE TITLE
tagcloud for kibana5.0

### ISSUE THREAD

**Issue by SunithaE** [stormpython/tagcloud#14]
Hi,
Is this plugin compatible for kibana 5.0 ? or is there a tagcloud/wordcloud for kibana5 ? 

 log   [11:44:08.679] [warning] Plugin "tagcloud" was disabled because it expeced Kibana version "0.1.0", and found "5.0.0".

Could someone advice on this please ?

**Comment by ranahaarb** [comment]
#12

**Comment by stormpython** [comment]
Closing this since it was addressed in #12.
