### ISSUE TITLE
Horizontal scrollbar

### ISSUE THREAD

**Issue by t3chn0m4g3** [stormpython/tagcloud#6]
I am running Kibana 4.4.1 and I do have the issue of a horizontal scrollbar showing up within the visualization which is independent of the visualization size, number of cloud items / size or its options.

Thank you very much for this great plugin :o)

**Comment by stormpython** [comment]
@t3chn0m4g3: can you provide me with the browser and browser version you are seeing this on, along with any other useful details that I may need to reproduce this bug.

Thanks.

**Comment by t3chn0m4g3** [comment]
Thanks for taking this on. The issue seems to be isolated to Windows and at least Chrome, will provide details as requested on thursday.

On a Mac (without mouse) the plugin works perfectly fine, though.

**Comment by stormpython** [comment]
@t3chn0m4g3 would you mind providing a screen shot. I don't actually have a Windows machine to test this on, but I will do my best to find a solution.

**Comment by t3chn0m4g3** [comment]
@stormpython Thanks, screenshot is attached. More on thursday.
![](http://i.imgur.com/SxP5i56.jpg)

**Comment by t3chn0m4g3** [comment]
@stormpython While gathering the requested information I got the latest Chrome Update (Version 49.0.2623.64 beta-m (64-bit)) and now it works perfectly and beautifully fine. To be really sure I checked with FireFox 44.0.2, Microsoft Edge 25.10586.0.0 and Opera 35.0.2066.79. Only Opera had a problem with the correct rendering of the plugin even with the latest beta (36.0.2130.2). Since Chrome, Edge and FF have no issues in their latest releases that's fine with me. Windows related testing was performed on Windows 10.0.10586.
On MacOS 10.11.3 I had no problems with Safari, Chrome, Opera and Firefox. The only issue I had was with Safari and when connecting a mouse which lead to horizontal scrollbars on some plugins (but not tagcloud). This should be related to some system settings.
On Linux (Ubuntu 15.10) I tested with Chrome (48.0.2564.109 (64-bit)), FireFox 44.0.1 and Opera beta (36.0.2130.2). Yet again Chrome and Opera did not render tagcloud correctly, upgrading to Chrome 49.0.2623.63 (Official Build) beta (64-bit) resolved the issue though which only leaves Opera without a viable solution on Linux and Windows.

**Comment by stormpython** [comment]
@t3chn0m4g3 thanks for the info. I will begin debugging this ASAP.

**Comment by stormpython** [comment]
This seems to be something that may be happening because of some changes in Kibana. I am seeing this happen in another custom visualization. I will play around with a fix here, but if it requires a fix in Kibana, I will submit a pull request there and reference this issue.
