### ISSUE TITLE
Exclude common words

### ISSUE THREAD

**Issue by rogeriobiondi** [stormpython/tagcloud#9]
Hello,

Is there any way to exclude common terms in a language, such as "a", "in", "the" and so on?

Thank you very much for your support.

Best regards,
Rogerio

**Comment by stormpython** [comment]
@rogeriobiondi the easiest way to do this if you are using kibana and elasticsearch is to configure analyzers in elasticsearch. You can read more about it [here](https://www.elastic.co/blog/found-text-analysis-part-1) or [here](https://www.elastic.co/guide/en/elasticsearch/reference/current/analysis-analyzers.html).
